export const regions = [
  {
    countryCode: 'AF',
    id: 45,
    mobilePrefix: '+93',
    name: 'Afghanistan',
    unit: 'USD',
  },
  {
    countryCode: 'AL',
    id: 46,
    mobilePrefix: '+355',
    name: 'Albania',
    unit: 'ALL',
  },
  {
    countryCode: 'DZ',
    id: 47,
    mobilePrefix: '+213',
    name: 'Algeria',
    unit: 'USD',
  },
  {
    countryCode: 'AD',
    id: 48,
    mobilePrefix: '+376',
    name: 'Andorra',
    unit: 'USD',
  },
  {
    countryCode: 'AO',
    id: 49,
    mobilePrefix: '+244',
    name: 'Angola',
    unit: 'USD',
  },
  {
    countryCode: 'AR',
    id: 37,
    mobilePrefix: '+54',
    name: 'Argentina',
    unit: 'ARS',
  },
  {
    countryCode: 'AM',
    id: 50,
    mobilePrefix: '+374',
    name: 'Armenia',
    unit: 'USD',
  },
  {
    countryCode: 'AW',
    id: 184,
    mobilePrefix: '+297',
    name: 'Aruba',
    unit: 'USD',
  },
  {
    countryCode: 'AU',
    id: 12,
    mobilePrefix: '+61',
    name: 'Australia',
    unit: 'AUD',
  },
  {
    countryCode: 'AT',
    id: 40,
    mobilePrefix: '+43',
    name: 'Austria',
    unit: 'AUD',
  },
  {
    countryCode: 'AZ',
    id: 51,
    mobilePrefix: '+994',
    name: 'Azerbaijan',
    unit: 'USD',
  },
  {
    countryCode: 'BS',
    id: 196,
    mobilePrefix: '+1',
    name: 'Bahamas',
    unit: 'USD',
  },
  {
    countryCode: 'BH',
    id: 52,
    mobilePrefix: '+973',
    name: 'Bahrain',
    unit: 'USD',
  },
  {
    countryCode: 'BD',
    id: 53,
    mobilePrefix: '+880',
    name: 'Bangladesh',
    unit: 'USD',
  },
  {
    countryCode: 'BB',
    id: 189,
    mobilePrefix: '+1',
    name: 'Barbados ',
    unit: 'USD',
  },
  {
    countryCode: 'BY',
    id: 54,
    mobilePrefix: '+375',
    name: 'Belarus',
    unit: 'USD',
  },
  {
    countryCode: 'BE',
    id: 55,
    mobilePrefix: '+32',
    name: 'Belgium',
    unit: 'EUR',
  },
  {
    countryCode: 'BZ',
    id: 191,
    mobilePrefix: '+501',
    name: 'belize',
    unit: 'USD',
  },
  {
    countryCode: 'BJ',
    id: 56,
    mobilePrefix: '+229',
    name: 'Benin',
    unit: 'CFA',
  },
  {
    countryCode: 'BM',
    id: 201,
    mobilePrefix: '+1',
    name: 'Bermuda',
    unit: 'BMD',
  },
  {
    countryCode: 'BT',
    id: 57,
    mobilePrefix: '+975',
    name: 'Bhutan',
    unit: 'USD',
  },
  {
    countryCode: 'BO',
    id: 58,
    mobilePrefix: '+591',
    name: 'Bolivia',
    unit: 'BOB',
  },
  {
    countryCode: 'BA',
    id: 59,
    mobilePrefix: '+387',
    name: 'Bosnia and Herzegovina',
    unit: 'USD',
  },
  {
    countryCode: 'BW',
    id: 60,
    mobilePrefix: '+267',
    name: 'Botswana',
    unit: 'USD',
  },
  {
    countryCode: 'BR',
    id: 10,
    mobilePrefix: '+55',
    name: 'Brasil',
    unit: 'BRL',
  },
  {
    countryCode: 'BN',
    id: 61,
    mobilePrefix: '+673',
    name: 'Brunei',
    unit: 'BND',
  },
  {
    countryCode: 'BG',
    id: 62,
    mobilePrefix: '+359',
    name: 'Bulgaria',
    unit: 'BGN',
  },
  {
    countryCode: 'BF',
    id: 63,
    mobilePrefix: '+226',
    name: 'Burkina Faso',
    unit: 'CFA',
  },
  {
    countryCode: 'BI',
    id: 64,
    mobilePrefix: '+257',
    name: 'Burundi',
    unit: 'USD',
  },
  {
    countryCode: 'KH',
    id: 65,
    mobilePrefix: '+855',
    name: 'Cambodia',
    unit: 'KHR',
  },
  {
    countryCode: 'CM',
    id: 66,
    mobilePrefix: '+237',
    name: 'Cameroon',
    unit: 'CFA',
  },
  {
    countryCode: 'CA',
    id: 9,
    mobilePrefix: '+1',
    name: 'Canada',
    unit: 'CAD',
  },
  {
    countryCode: 'CV',
    id: 67,
    mobilePrefix: '+238',
    name: 'Cape Verde',
    unit: 'USD',
  },
  {
    countryCode: 'KY',
    id: 188,
    mobilePrefix: '+1',
    name: 'Cayman Islands',
    unit: 'USD',
  },
  {
    countryCode: 'CF',
    id: 68,
    mobilePrefix: '+236',
    name: 'Central Africa',
    unit: 'CFA',
  },
  {
    countryCode: 'TD',
    id: 69,
    mobilePrefix: '+235',
    name: 'Chad',
    unit: 'CFA',
  },
  {
    countryCode: 'CL',
    id: 70,
    mobilePrefix: '+56',
    name: 'Chile',
    unit: 'CLP',
  },
  {
    countryCode: 'CN',
    id: 13,
    mobilePrefix: '+86',
    name: 'China',
    unit: 'CNY',
  },
  {
    countryCode: 'CO',
    id: 24,
    mobilePrefix: '+57',
    name: 'Colombia',
    unit: 'COP',
  },
  {
    countryCode: 'KM',
    id: 71,
    mobilePrefix: '+269',
    name: 'Comoros',
    unit: 'USD',
  },
  {
    countryCode: 'CR',
    id: 72,
    mobilePrefix: '+506',
    name: 'Costa Rica',
    unit: 'CRC',
  },
  {
    countryCode: 'HR',
    id: 73,
    mobilePrefix: '+385',
    name: 'Croatia',
    unit: 'HRK',
  },
  {
    countryCode: 'CU',
    id: 74,
    mobilePrefix: '+53',
    name: 'Cuba',
    unit: 'USD',
  },
  {
    countryCode: 'CW',
    id: 183,
    mobilePrefix: '+599',
    name: 'Curacao',
    unit: 'USD',
  },
  {
    countryCode: 'CY',
    id: 20,
    mobilePrefix: '+357',
    name: 'Cyprus',
    unit: 'CYP',
  },
  {
    countryCode: 'CZ',
    id: 75,
    mobilePrefix: '+420',
    name: 'Czech Republic',
    unit: 'CZK',
  },
  {
    countryCode: 'CD',
    id: 76,
    mobilePrefix: '+243',
    name: 'Democratic Republic of Congo',
    unit: 'USD',
  },
  {
    countryCode: 'DK',
    id: 41,
    mobilePrefix: '+45',
    name: 'Denmark',
    unit: 'DKK',
  },
  {
    countryCode: 'DJ',
    id: 77,
    mobilePrefix: '+253',
    name: 'Djibouti',
    unit: 'USD',
  },
  {
    countryCode: 'DO',
    id: 186,
    mobilePrefix: '+1',
    name: 'Dominican Republic',
    unit: 'DOP',
  },
  {
    countryCode: 'TL',
    id: 78,
    mobilePrefix: '+670',
    name: 'East Timor',
    unit: 'USD',
  },
  {
    countryCode: 'EC',
    id: 79,
    mobilePrefix: '+593',
    name: 'Ecuador',
    unit: 'USD',
  },
  {
    countryCode: 'EG',
    id: 80,
    mobilePrefix: '+20',
    name: 'Egypt',
    unit: 'USD',
  },
  {
    countryCode: 'SV',
    id: 192,
    mobilePrefix: '+503',
    name: 'El Salvador',
    unit: 'USD',
  },
  {
    countryCode: 'GQ',
    id: 81,
    mobilePrefix: '+240',
    name: 'Equatorial Guinea',
    unit: 'CFA',
  },
  {
    countryCode: 'ER',
    id: 82,
    mobilePrefix: '+291',
    name: 'Eritrea',
    unit: 'USD',
  },
  {
    countryCode: 'EE',
    id: 83,
    mobilePrefix: '+372',
    name: 'Estonia',
    unit: 'EUR',
  },
  {
    countryCode: 'ET',
    id: 84,
    mobilePrefix: '+251',
    name: 'Ethiopia',
    unit: 'USD',
  },
  {
    countryCode: 'FJ',
    id: 85,
    mobilePrefix: '+679',
    name: 'Fiji',
    unit: 'USD',
  },
  {
    countryCode: 'FI',
    id: 86,
    mobilePrefix: '+358',
    name: 'Finland',
    unit: 'EUR',
  },
  {
    countryCode: 'FR',
    id: 87,
    mobilePrefix: '+33',
    name: 'France',
    unit: 'EUR',
  },
  {
    countryCode: 'PF',
    id: 198,
    mobilePrefix: '+689',
    name: 'French Polynesia',
    unit: 'USD',
  },
  {
    countryCode: 'GA',
    id: 88,
    mobilePrefix: '+241',
    name: 'Gabon Republic',
    unit: 'CFA',
  },
  {
    countryCode: 'GM',
    id: 89,
    mobilePrefix: '+220',
    name: 'Gambia',
    unit: 'USD',
  },
  {
    countryCode: 'GE',
    id: 90,
    mobilePrefix: '+995',
    name: 'Georgia',
    unit: 'USD',
  },
  {
    countryCode: 'DE',
    id: 91,
    mobilePrefix: '+49',
    name: 'Germany',
    unit: 'EUR',
  },
  {
    countryCode: 'GH',
    id: 29,
    mobilePrefix: '+233',
    name: 'Ghana',
    unit: 'USD',
  },
  {
    countryCode: 'GI',
    id: 93,
    mobilePrefix: '+350',
    name: 'Gibraltar',
    unit: 'USD',
  },
  {
    countryCode: 'GR',
    id: 21,
    mobilePrefix: '+30',
    name: 'Greece',
    unit: 'EUR',
  },
  {
    countryCode: 'GD',
    id: 94,
    mobilePrefix: '+1',
    name: 'Grenada',
    unit: 'XCD',
  },
  {
    countryCode: 'GP',
    id: 199,
    mobilePrefix: '+590',
    name: 'Guadeloupe',
    unit: 'EUR',
  },
  {
    countryCode: 'GT',
    id: 34,
    mobilePrefix: '+502',
    name: 'Guatemala',
    unit: 'GTQ',
  },
  {
    countryCode: 'GN',
    id: 95,
    mobilePrefix: '+224',
    name: 'Guinea',
    unit: 'USD',
  },
  {
    countryCode: 'GW',
    id: 96,
    mobilePrefix: '+245',
    name: 'Guinea-Bissau',
    unit: 'CFA',
  },
  {
    countryCode: 'GY',
    id: 195,
    mobilePrefix: '+592',
    name: 'Guyana',
    unit: 'USD',
  },
  {
    countryCode: 'HT',
    id: 97,
    mobilePrefix: '+509',
    name: 'Haiti',
    unit: 'USD',
  },
  {
    countryCode: 'HN',
    id: 98,
    mobilePrefix: '+504',
    name: 'Honduras',
    unit: 'USD',
  },
  {
    countryCode: 'HK',
    id: 14,
    mobilePrefix: '+852',
    name: 'Hong Kong',
    unit: 'HKD',
  },
  {
    countryCode: 'HU',
    id: 38,
    mobilePrefix: '+36',
    name: 'Hungary',
    unit: 'HUF',
  },
  {
    countryCode: 'IS',
    id: 99,
    mobilePrefix: '+354',
    name: 'Iceland',
    unit: 'ISK',
  },
  {
    countryCode: 'IN',
    id: 7,
    mobilePrefix: '+91',
    name: 'India',
    unit: 'INR',
  },
  {
    countryCode: 'ID',
    id: 2,
    mobilePrefix: '+62',
    name: 'Indonesia',
    unit: 'IDR',
  },
  {
    countryCode: 'IR',
    id: 100,
    mobilePrefix: '+98',
    name: 'Iran',
    unit: 'USD',
  },
  {
    countryCode: 'IQ',
    id: 101,
    mobilePrefix: '+964',
    name: 'Iraq',
    unit: 'USD',
  },
  {
    countryCode: 'IE',
    id: 102,
    mobilePrefix: '+353',
    name: 'Ireland',
    unit: 'EUR',
  },
  {
    countryCode: 'IM',
    id: 200,
    mobilePrefix: '+44',
    name: 'Isle of Man',
    unit: 'GBP',
  },
  {
    countryCode: 'IL',
    id: 103,
    mobilePrefix: '+972',
    name: 'Israel',
    unit: 'ILS',
  },
  {
    countryCode: 'IT',
    id: 104,
    mobilePrefix: '+39',
    name: 'Italy',
    unit: 'EUR',
  },
  {
    countryCode: 'CI',
    id: 105,
    mobilePrefix: '+225',
    name: 'Ivory Coast',
    unit: 'CFA',
  },
  {
    countryCode: 'JM',
    id: 106,
    mobilePrefix: '+1',
    name: 'Jamaica',
    unit: 'USD',
  },
  {
    countryCode: 'JP',
    id: 6,
    mobilePrefix: '+81',
    name: 'Japan',
    unit: 'JPY',
  },
  {
    countryCode: 'JO',
    id: 107,
    mobilePrefix: '+962',
    name: 'Jordan',
    unit: 'USD',
  },
  {
    countryCode: 'KZ',
    id: 108,
    mobilePrefix: '+7',
    name: 'Kazakhstan',
    unit: 'USD',
  },
  {
    countryCode: 'KE',
    id: 28,
    mobilePrefix: '+254',
    name: 'Kenya',
    unit: 'USD',
  },
  {
    countryCode: 'XK',
    id: 109,
    mobilePrefix: '+383',
    name: 'Kosovo',
    unit: 'EUR',
  },
  {
    countryCode: 'KW',
    id: 110,
    mobilePrefix: '+965',
    name: 'Kuwait',
    unit: 'USD',
  },
  {
    countryCode: 'KG',
    id: 111,
    mobilePrefix: '+996',
    name: 'Kyrgyzstan',
    unit: 'USD',
  },
  {
    countryCode: 'LA',
    id: 112,
    mobilePrefix: '+856',
    name: 'Laos',
    unit: 'USD',
  },
  {
    countryCode: 'LV',
    id: 113,
    mobilePrefix: '+371',
    name: 'Latvia',
    unit: 'EUR',
  },
  {
    countryCode: 'LB',
    id: 114,
    mobilePrefix: '+961',
    name: 'Lebanon',
    unit: 'USD',
  },
  {
    countryCode: 'LS',
    id: 115,
    mobilePrefix: '+266',
    name: 'Lesotho',
    unit: 'USD',
  },
  {
    countryCode: 'LR',
    id: 116,
    mobilePrefix: '+231',
    name: 'Liberia',
    unit: 'USD',
  },

  {
    countryCode: 'LI',
    id: 118,
    mobilePrefix: '+423',
    name: 'Liechtenstein',
    unit: 'CHF',
  },
  {
    countryCode: 'LT',
    id: 119,
    mobilePrefix: '+370',
    name: 'Lithuania',
    unit: 'EUR',
  },
  {
    countryCode: 'LU',
    id: 120,
    mobilePrefix: '+352',
    name: 'Luxembourg',
    unit: 'EUR',
  },
  {
    countryCode: 'MO',
    id: 121,
    mobilePrefix: '+853',
    name: 'Macau',
    unit: 'USD',
  },
  {
    countryCode: 'MK',
    id: 122,
    mobilePrefix: '+389',
    name: 'Macedonia',
    unit: 'USD',
  },
  {
    countryCode: 'MG',
    id: 123,
    mobilePrefix: '+261',
    name: 'Madagascar',
    unit: 'USD',
  },
  {
    countryCode: 'MW',
    id: 124,
    mobilePrefix: '+265',
    name: 'Malawi',
    unit: 'USD',
  },
  {
    countryCode: 'MV',
    id: 125,
    mobilePrefix: '+960',
    name: 'Maldives',
    unit: 'USD',
  },
  {
    countryCode: 'ML',
    id: 126,
    mobilePrefix: '+223',
    name: 'Mali Republic',
    unit: 'CFA',
  },
  {
    countryCode: 'MT',
    id: 27,
    mobilePrefix: '+356',
    name: 'Malta',
    unit: 'EUR',
  },
  {
    countryCode: 'MR',
    id: 127,
    mobilePrefix: '+222',
    name: 'Mauritania',
    unit: 'USD',
  },
  {
    countryCode: 'MU',
    id: 128,
    mobilePrefix: '+230',
    name: 'Mauritius',
    unit: 'MUR',
  },
  {
    countryCode: 'MX',
    id: 11,
    mobilePrefix: '+52',
    name: 'Mexico',
    unit: 'MXN',
  },
  {
    countryCode: 'MD',
    id: 129,
    mobilePrefix: '+373',
    name: 'Moldova',
    unit: 'USD',
  },
  {
    countryCode: 'MC',
    id: 130,
    mobilePrefix: '+377',
    name: 'Monaco',
    unit: 'EUR',
  },
  {
    countryCode: 'MN',
    id: 131,
    mobilePrefix: '+976',
    name: 'Mongolia',
    unit: 'USD',
  },
  {
    countryCode: 'ME',
    id: 132,
    mobilePrefix: '+382',
    name: 'Montenegro',
    unit: 'EUR',
  },
  {
    countryCode: 'MA',
    id: 133,
    mobilePrefix: '+212',
    name: 'Morocco',
    unit: 'USD',
  },
  {
    countryCode: 'MZ',
    id: 134,
    mobilePrefix: '+258',
    name: 'Mozambique',
    unit: 'USD',
  },
  {
    countryCode: 'MM',
    id: 135,
    mobilePrefix: '+95',
    name: 'Myanmar',
    unit: 'USD',
  },
  {
    countryCode: 'NA',
    id: 136,
    mobilePrefix: '+264',
    name: 'Namibia',
    unit: 'USD',
  },
  {
    countryCode: 'NP',
    id: 137,
    mobilePrefix: '+977',
    name: 'Nepal',
    unit: 'USD',
  },
  {
    countryCode: 'NL',
    id: 17,
    mobilePrefix: '+31',
    name: 'Netherlands',
    unit: 'EUR',
  },
  {
    countryCode: 'NZ',
    id: 138,
    mobilePrefix: '+64',
    name: 'New Zealand',
    unit: 'NZD',
  },
  {
    countryCode: 'NI',
    id: 194,
    mobilePrefix: '+505',
    name: 'Nicaragua',
    unit: 'USD',
  },
  {
    countryCode: 'NE',
    id: 139,
    mobilePrefix: '+227',
    name: 'Niger',
    unit: 'CFA',
  },
  {
    countryCode: 'NG',
    id: 26,
    mobilePrefix: '+234',
    name: 'Nigeria',
    unit: 'NGN',
  },
  {
    countryCode: 'KP',
    id: 140,
    mobilePrefix: '+850',
    name: 'North Korea',
    unit: 'USD',
  },
  {
    countryCode: 'NO',
    id: 32,
    mobilePrefix: '+47',
    name: 'Norway',
    unit: 'NOK',
  },
  {
    countryCode: 'OM',
    id: 141,
    mobilePrefix: '+968',
    name: 'Oman',
    unit: 'USD',
  },
  {
    countryCode: 'PK',
    id: 142,
    mobilePrefix: '+92',
    name: 'Pakistan',
    unit: 'PKR',
  },
  {
    countryCode: 'PW',
    id: 143,
    mobilePrefix: '+680',
    name: 'Palau',
    unit: 'USD',
  },
  {
    countryCode: 'PS',
    id: 197,
    mobilePrefix: '+970',
    name: 'Palestine',
    unit: 'USD',
  },
  {
    countryCode: 'PA',
    id: 144,
    mobilePrefix: '+507',
    name: 'Panama',
    unit: 'USD',
  },
  {
    countryCode: 'PG',
    id: 22,
    mobilePrefix: '+675',
    name: 'Papua New Guinea',
    unit: 'PGK',
  },
  {
    countryCode: 'PY',
    id: 145,
    mobilePrefix: '+595',
    name: 'Paraguay',
    unit: 'USD',
  },
  {
    countryCode: 'PE',
    id: 39,
    mobilePrefix: '+51',
    name: 'Peru',
    unit: 'PEN',
  },
  {
    countryCode: 'PH',
    id: 44,
    mobilePrefix: '+63',
    name: 'Philippines',
    unit: 'PHP',
  },
  {
    countryCode: 'PL',
    id: 146,
    mobilePrefix: '+48',
    name: 'Poland',
    unit: 'PLN',
  },
  {
    countryCode: 'PT',
    id: 147,
    mobilePrefix: '+351',
    name: 'Portugal',
    unit: 'EUR',
  },
  {
    countryCode: 'PR',
    id: 193,
    mobilePrefix: '+1',
    name: 'Puerto Rico',
    unit: 'USD',
  },
  {
    countryCode: 'QA',
    id: 148,
    mobilePrefix: '+974',
    name: 'Qatar',
    unit: 'USD',
  },
  {
    countryCode: 'CG',
    id: 149,
    mobilePrefix: '+242',
    name: 'Republic of the Congo',
    unit: 'CFA',
  },
  {
    countryCode: 'RO',
    id: 150,
    mobilePrefix: '+40',
    name: 'Romania',
    unit: 'RON',
  },
  {
    countryCode: 'RU',
    id: 151,
    mobilePrefix: '+7',
    name: 'Russia',
    unit: 'RUB',
  },
  {
    countryCode: 'RW',
    id: 152,
    mobilePrefix: '+250',
    name: 'Rwanda',
    unit: 'RWF',
  },
  {
    countryCode: 'WS',
    id: 153,
    mobilePrefix: '+685',
    name: 'Samoa',
    unit: 'USD',
  },
  {
    countryCode: 'SM',
    id: 154,
    mobilePrefix: '+378',
    name: 'San Marino',
    unit: 'EUR',
  },
  {
    countryCode: 'ST',
    id: 155,
    mobilePrefix: '+239',
    name: 'Sao Tome',
    unit: 'USD',
  },
  {
    countryCode: 'SA',
    id: 156,
    mobilePrefix: '+966',
    name: 'Saudi Arabia',
    unit: 'USD',
  },
  {
    countryCode: 'SN',
    id: 157,
    mobilePrefix: '+221',
    name: 'Senegal',
    unit: 'CFA',
  },
  {
    countryCode: 'RS',
    id: 158,
    mobilePrefix: '+381',
    name: 'Serbia',
    unit: 'USD',
  },
  {
    countryCode: 'SC',
    id: 159,
    mobilePrefix: '+248',
    name: 'Seychelles',
    unit: 'SCR',
  },
  {
    countryCode: 'SL',
    id: 160,
    mobilePrefix: '+232',
    name: 'Sierra Leone',
    unit: 'USD',
  },
  {
    countryCode: 'SG',
    id: 5,
    mobilePrefix: '+65',
    name: 'Singapore',
    unit: 'SGD',
  },
  {
    countryCode: 'SX',
    id: 185,
    mobilePrefix: '+1',
    name: 'Sint Maarten',
    unit: 'USD',
  },
  {
    countryCode: 'SK',
    id: 161,
    mobilePrefix: '+421',
    name: 'Slovakia',
    unit: 'EUR',
  },
  {
    countryCode: 'SI',
    id: 35,
    mobilePrefix: '+386',
    name: 'Slovenia',
    unit: 'EUR',
  },
  {
    countryCode: 'SO',
    id: 162,
    mobilePrefix: '+252',
    name: 'Somalia',
    unit: 'USD',
  },
  {
    countryCode: 'ZA',
    id: 163,
    mobilePrefix: '+27',
    name: 'South Africa',
    unit: 'ZAR',
  },
  {
    countryCode: 'KR',
    id: 3,
    mobilePrefix: '+82',
    name: 'South Korea',
    unit: 'KRW',
  },
  {
    countryCode: 'SS',
    id: 164,
    mobilePrefix: '+211',
    name: 'South Sudan',
    unit: 'SSP',
  },
  {
    countryCode: 'ES',
    id: 36,
    mobilePrefix: '+34',
    name: 'Spain',
    unit: 'EUR',
  },
  {
    countryCode: 'LK',
    id: 165,
    mobilePrefix: '+94',
    name: 'Sri Lanka',
    unit: 'USD',
  },
  {
    countryCode: 'SD',
    id: 166,
    mobilePrefix: '+249',
    name: 'Sudan',
    unit: 'USD',
  },
  {
    countryCode: 'SR',
    id: 187,
    mobilePrefix: '+597',
    name: 'Suriname',
    unit: 'USD',
  },
  {
    countryCode: 'SZ',
    id: 167,
    mobilePrefix: '+268',
    name: 'Swaziland',
    unit: 'USD',
  },
  {
    countryCode: 'SE',
    id: 43,
    mobilePrefix: '+46',
    name: 'Sweden',
    unit: 'SEK',
  },
  {
    countryCode: 'CH',
    id: 42,
    mobilePrefix: '+41',
    name: 'Switzerland',
    unit: 'CHF',
  },
  {
    countryCode: 'SY',
    id: 168,
    mobilePrefix: '+963',
    name: 'Syria',
    unit: 'USD',
  },
  {
    countryCode: 'TW',
    id: 15,
    mobilePrefix: '+886',
    name: 'Taiwan',
    unit: 'TWD',
  },
  {
    countryCode: 'TJ',
    id: 169,
    mobilePrefix: '+992',
    name: 'Tajikistan',
    unit: 'USD',
  },
  {
    countryCode: 'TZ',
    id: 170,
    mobilePrefix: '+255',
    name: 'Tanzania',
    unit: 'USD',
  },
  {
    countryCode: 'TH',
    id: 8,
    mobilePrefix: '+66',
    name: 'Thailand',
    unit: 'THB',
  },
  {
    countryCode: 'TG',
    id: 171,
    mobilePrefix: '+228',
    name: 'Togo',
    unit: 'CFA',
  },
  {
    countryCode: 'TT',
    id: 202,
    mobilePrefix: '+1',
    name: 'Trinidad and Tobago',
    unit: 'TTD',
  },
  {
    countryCode: 'TN',
    id: 172,
    mobilePrefix: '+216',
    name: 'Tunisia',
    unit: 'USD',
  },
  {
    countryCode: 'TR',
    id: 173,
    mobilePrefix: '+90',
    name: 'Turkey',
    unit: 'TRY',
  },
  {
    countryCode: 'TM',
    id: 174,
    mobilePrefix: '+993',
    name: 'Turkmenistan',
    unit: 'TMT',
  },
  {
    countryCode: 'TC',
    id: 190,
    mobilePrefix: '+1',
    name: 'Turks and Caicos Islands',
    unit: 'USD',
  },
  {
    countryCode: 'UG',
    id: 30,
    mobilePrefix: '+256',
    name: 'Uganda',
    unit: 'USD',
  },
  {
    countryCode: 'UA',
    id: 175,
    mobilePrefix: '+380',
    name: 'Ukraine',
    unit: 'UAH',
  },
  {
    countryCode: 'AE',
    id: 25,
    mobilePrefix: '+971',
    name: 'United Arab Emirates',
    unit: 'AED',
  },
  {
    countryCode: 'GB',
    id: 4,
    mobilePrefix: '+44',
    name: 'United Kingdom',
    unit: 'GBP',
  },
  {
    countryCode: 'US',
    id: 1,
    mobilePrefix: '+1',
    name: 'United States',
    unit: 'USD',
  },
  {
    countryCode: 'UY',
    id: 176,
    mobilePrefix: '+598',
    name: 'Uruguay',
    unit: 'USD',
  },
  {
    countryCode: 'UZ',
    id: 177,
    mobilePrefix: '+998',
    name: 'Uzbekistan',
    unit: 'USD',
  },
  {
    countryCode: 'VA',
    id: 178,
    mobilePrefix: '+379',
    name: 'Vatican City',
    unit: 'EUR',
  },
  {
    countryCode: 'VE',
    id: 33,
    mobilePrefix: '+58',
    name: 'Venezuela',
    unit: 'USD',
  },
  {
    countryCode: 'VN',
    id: 179,
    mobilePrefix: '+84',
    name: 'Vietnam',
    unit: 'VND',
  },
  {
    countryCode: 'EH',
    id: 180,
    mobilePrefix: '+212',
    name: 'Western Sahara',
    unit: 'USD',
  },
  {
    countryCode: 'YE',
    id: 181,
    mobilePrefix: '+967',
    name: 'Yemen',
    unit: 'USD',
  },
  {
    countryCode: 'ZM',
    id: 182,
    mobilePrefix: '+260',
    name: 'Zambia',
    unit: 'USD',
  },
  {
    countryCode: 'ZW',
    id: 31,
    mobilePrefix: '+263',
    name: 'Zimbabwe',
    unit: 'USD',
  },
]
